name       : albert
version    : 0.9.4
release    : 4
source     :
    - https://github.com/ManuelSchneid3r/albert/archive/v0.9.4.tar.gz : c514d3a949b792f536c5a682f4f9127c014ce8ddf60938584efe81c568724dad
license    : GPL-3.0
component  : desktop
summary    : A DE agnostic omnilauncher
description: |
    Access everything with virtually zero effort. Run applications, open files or their paths, open bookmarks in your browser, search the web, calculate things and a lot more ...
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(muparser)
    - pkgconfig(x11)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
