name       : albert
version    : 0.11.2
release    : 10
source     :
    - https://github.com/albertlauncher/albert/archive/v0.11.2.tar.gz : 991088cef2c4b7dc27b01e703bb7cb13f7f2dac928f0f9c235b2bd52d362a4e7
license    : GPL-3.0
component  : desktop
summary    : A DE agnostic omnilauncher
description: |
    Access everything with virtually zero effort. Run applications, open files or their paths, open bookmarks in your browser, search the web, calculate things and a lot more ...
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(muparser)
    - pkgconfig(x11)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
