name       : albert
version    : 0.11.1
release    : 9
source     :
    - https://github.com/albertlauncher/albert/archive/v0.11.1.tar.gz : d214b73bf154bef59d36a4b128493b5dd9ecc7ba059a606f9b4659b57741f390
license    : GPL-3.0
component  : desktop
summary    : A DE agnostic omnilauncher
description: |
    Access everything with virtually zero effort. Run applications, open files or their paths, open bookmarks in your browser, search the web, calculate things and a lot more ...
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(muparser)
    - pkgconfig(x11)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
