name       : albert
version    : 0.10.1
release    : 7
source     :
    - https://github.com/albertlauncher/albert/archive/v0.10.1.tar.gz : e7e178503fcaa40741104add022234a8ef8fb849f0ae781c230c52d75b3787db
license    : GPL-3.0
component  : desktop
summary    : A DE agnostic omnilauncher
description: |
    Access everything with virtually zero effort. Run applications, open files or their paths, open bookmarks in your browser, search the web, calculate things and a lot more ...
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(muparser)
    - pkgconfig(x11)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
