name       : albert
version    : 0.12.0
release    : 11
source     :
    - https://github.com/albertlauncher/albert/archive/v0.12.0.tar.gz : e1ec7783b6cc22e5ed28d2f1ac6148528cb3eb734f139945b49d44e07770d9c8
license    : GPL-3.0
component  : desktop
summary    : A DE agnostic omnilauncher
description: |
    Access everything with virtually zero effort. Run applications, open files or their paths, open bookmarks in your browser, search the web, calculate things and a lot more ...
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(muparser)
    - pkgconfig(x11)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
