name       : albert
version    : 0.13.1
release    : 14
source     :
    - git|https://github.com/albertlauncher/albert.git : v0.13.1
license    : GPL-3.0
component  : desktop
summary    : A DE agnostic omnilauncher
description: |
    Access everything with virtually zero effort. Run applications, open files or their paths, open bookmarks in your browser, search the web, calculate things and a lot more ...
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(muparser)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake -DBUILD_VIRTUALBOX=OFF .
build      : |
    %make
install    : |
    %make_install

