name       : albert
version    : 0.10.3
release    : 8
source     :
    - https://github.com/albertlauncher/albert/archive/v0.10.3.tar.gz : d58cfc12d0956db75b07b074c08ab1b40d14e5df06fdcbe9f492fa48028f61ac
license    : GPL-3.0
component  : desktop
summary    : A DE agnostic omnilauncher
description: |
    Access everything with virtually zero effort. Run applications, open files or their paths, open bookmarks in your browser, search the web, calculate things and a lot more ...
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(muparser)
    - pkgconfig(x11)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
